name: SqlInsights Windows Matrix

on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  Windows-Job:
    name: ${{ matrix.SQL }}
    runs-on: "windows-${{ matrix.HOST }}"
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix: ${{ fromJson(inputs.matrix) }}
    
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bootstrap
        uses: devizer/devops-library@main
      - name: 'Store Job Name'
        shell: bash
        run: 'echo ${{ matrix.SQL }} | tee $SYSTEM_ARTIFACTSDIRECTORY/JOB-NAME.TXT'
      - name: Download Pre-Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Pre-Build
          path: "${{ github.workspace }}/Goods"

      - name: Setup Variables
        shell: pwsh
        run: |
          . .\scripts\CI-Steps\Functions.ps1
          Say "Variables for GitHub Actions"
          
          $SQL_IMAGE_TAG="";
          if ("${{ matrix.SQL_CONTAINER_SUFFIX }}") { $SQL_IMAGE_TAG="ltsc${{ matrix.SQL_CONTAINER_SUFFIX }}"; }
          Set-Var "SQL_IMAGE_TAG" "$SQL_IMAGE_TAG"

          $SQL="${{ matrix.SQL }}: MSSQLSERVER"
          Set-Var "SQL" "$SQL"

          $SQL_IMAGE_ISOLATION="hyperv"
          Set-Var "SQL_IMAGE_ISOLATION" "$SQL_IMAGE_ISOLATION"

          $SQL_INSTANCE_NAME="(local)"
          if ("$SQL" -match "LocalDB") { $SQL_INSTANCE_NAME='(LocalDB)\MSSQLLocalDB'; }
          Set-Var "SQL_INSTANCE_NAME" "$SQL_INSTANCE_NAME"

      - name: Show Arguments and Pre-Build Content
        run: |
          Import-DevOps
          Say "SQL: [${{ matrix.SQL }}]"
          foreach($f in ".\Goods", ".\Goods\w3api", ".\Goods\w3api\wwwroot", "$ENV:SYSTEM_ARTIFACTSDIRECTORY") {
             Say "$f content"
             ls $f | ft -autosize
          }

      - name: 'Tune Docker'
        if: ${{ env.SQL_IMAGE_TAG != '' }}
        run: Import-DevOps; Run-Remote-Script https://raw.githubusercontent.com/devizer/glist/master/Move-Docker-to-SSD-for-Windows-On-Microsoft-Hosted-Build-Agent.ps1
      
      - name: 'List Perfmormance Counters'
        run: (Get-Counter -ListSet *).Paths | Where-Object { $_ -like "*Transfers*" }

      - name: 'Show Transfer for 20 seconds'
        run: Get-Counter -Counter "\PhysicalDisk(_total)\Disk Transfers/sec" -SampleInterval 1 -MaxSamples 7

      - name: Pull Docker Image
        if: ${{ env.SQL_IMAGE_TAG != '' }}
        shell: bash
        run: . '.\scripts\CI-Steps\0A-Pull-Docker-Image.sh'

      - name: RUN Container
        uses: nick-fields/retry@v3
        if: ${{ env.SQL_IMAGE_TAG != '' }}
        with:
          timeout_minutes: 10
          max_attempts: 4
          shell: pwsh
          retry_wait_seconds: 2
          command: . .\scripts\CI-Steps\0B-SETUP-Windows-Container.ps1
      
      - name: '1.1-Install-Module.ps1 '
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 1.1-Install-Module.ps1
        if: always()

      - name: '2-Install-DotNet.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 2-Install-DotNet.ps1
        if: always()

      - name: '3-Install-SQL-Server.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 3-Install-SQL-Server.ps1
        if: always()

      - name: Publish SQL Setup Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: SQL Setup Logs ${{ matrix.SQL }} ${{ github.run_attempt }}
          path: ${{ env.SYSTEM_ARTIFACTSDIRECTORY }}/SQL Setup Logs
          overwrite: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'If ${{ matrix.SQL }}'
          path: ${{ env.SYSTEM_ARTIFACTSDIRECTORY }}
          overwrite: true
          compression-level: 9
