name: SqlInsights Windows Matrix

on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string
      SQL_SET_SIZE:
        required: true
        type: string
      HOST_VERSION:
        required: true
        type: string

jobs:
  The-Job:
    name: ${{ matrix.JOB_TITLE }}
    # OS: Windows|Ubuntu, # HOST: 2022, 2025, 22.04, 24.04
    runs-on: "${{ matrix.RUNS_ON }}"
    timeout-minutes: 70
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix: ${{ fromJson(inputs.matrix) }}
    
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bootstrap
        uses: devizer/devops-library@main
      - name: 'Store Job Name'
        shell: bash
        run: 'echo ${{ matrix.JOB_TITLE }} | tee $SYSTEM_ARTIFACTSDIRECTORY/JOB-NAME.TXT; printenv | sort'
      - name: Download Pre-Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Pre-Build
          path: "${{ github.workspace }}/Goods"

      - name: Setup Variables
        shell: pwsh
        run: |
          . .\scripts\CI-Steps\Functions.ps1
          Say "Variables for GitHub Actions"
          
          $SQL_IMAGE_TAG="";
          if ("${{ matrix.SQL_CONTAINER_SUFFIX }}") { 
            if ((Get-Os-Platform) -eq "Windows") {
               $SQL_IMAGE_TAG="ltsc${{ matrix.SQL_CONTAINER_SUFFIX }}"; 
            } Else {
               $SQL_IMAGE_TAG="${{ matrix.SQL_CONTAINER_SUFFIX }}-latest"; 
            }
          }
          Set-Var "SQL_IMAGE_TAG" "$SQL_IMAGE_TAG"

          $SQL="${{ matrix.SQL }}"
          if ($SQL -notmatch "LocalDB" -and "${{ matrix.OS }}" -eq "Windows") { $SQL="${{ matrix.SQL }}: MSSQLSERVER" }
          Set-Var "SQL" "$SQL"

          # Windows Only
          $SQL_IMAGE_ISOLATION="hyperv"
          Set-Var "SQL_IMAGE_ISOLATION" "$SQL_IMAGE_ISOLATION"

          $SQL_INSTANCE_NAME="(local)"
          if ("$SQL" -match "LocalDB") { $SQL_INSTANCE_NAME='(LocalDB)\MSSQLLocalDB'; }
          Set-Var "SQL_INSTANCE_NAME" "$SQL_INSTANCE_NAME"

          Set-Var "RUNS_ON" "${{ matrix.RUNS_ON }}"
          Set-Var "OS" "${{ matrix.OS }}"

          $docker_image_full = if ($ENV:OS -eq "Windows") { "devizervlad/iis-net4x-net35:$($ENV:SQL_IMAGE_TAG)" } Else { "mcr.microsoft.com/mssql/server:$($ENV:SQL_IMAGE_TAG)" }
          Set-Var "DOCKER_IMAGE_FULL" "$docker_image_full"

          Set-Var "LINUX_MSSQL_PID" "${{ matrix.LINUX_MSSQL_PID }}"


      - name: Show Arguments and Pre-Build Content
        run: |
          Import-DevOps
          Write-Line -TextGreen "SQL:                  [${{ matrix.SQL }}]"
          Write-Line -TextGreen "RUNS_ON:              [${{ matrix.RUNS_ON }}]"
          Write-Line -TextGreen "OS:                   [${{ matrix.OS }}]"
          Write-Line -TextGreen "HOST:                 [${{ matrix.HOST }}]"
          Write-Line -TextGreen "LINUX_MSSQL_PID:      [${{ matrix.LINUX_MSSQL_PID }}]"
          Write-Line -TextGreen "DOCKER_IMAGE_FULL:    [$ENV:DOCKER_IMAGE_FULL]"
          Write-Line -TextGreen "SQL_CONTAINER_SUFFIX: [${{ matrix.SQL_CONTAINER_SUFFIX }}]"
          
          foreach($f in ".\Goods", ".\Goods\w3api", ".\Goods\w3api\wwwroot", "$ENV:SYSTEM_ARTIFACTSDIRECTORY") {
             Say "$f content"
             Get-ChildItem $f | ft -autosize
          }

      - name: 'Tune Windows Docker'
        if: ${{ env.SQL_IMAGE_TAG != '' && env.OS == 'Windows' }}
        run: Import-DevOps; Run-Remote-Script https://raw.githubusercontent.com/devizer/glist/master/Move-Docker-to-SSD-for-Windows-On-Microsoft-Hosted-Build-Agent.ps1
      
      - name: 'List Perfmormance Counters'
        if: ${{ matrix.OS == 'Windows' }}
        run: (Get-Counter -ListSet *).Paths | Where-Object { $_ -like "*Transfers*" }

      - name: 'Show DISK IO for 20 seconds'
        if: ${{ matrix.OS == 'Windows' }}
        run: Get-Counter -Counter "\PhysicalDisk(_total)\Disk Transfers/sec" -SampleInterval 1 -MaxSamples 7 -EA SilentlyContinue

      - name: Pull Docker Image
        if: ${{ env.SQL_IMAGE_TAG != '' }}
        shell: bash
        run: . './scripts/CI-Steps/0A-Pull-Docker-Image.sh'

      - name: RUN Windows Container
        uses: nick-fields/retry@v3
        if: ${{ env.SQL_IMAGE_TAG != '' && matrix.OS == 'Windows' }}
        with:
          timeout_minutes: 10
          max_attempts: 4
          shell: pwsh
          retry_wait_seconds: 2
          command: $ErrorActionPreference="Stop"; . .\scripts\CI-Steps\0B-SETUP-Windows-Container.ps1
      
      - name: RUN SQL Server ${{ matrix.JOB_TITLE }} Linux Container
        shell: bash
        if: ${{ env.SQL_IMAGE_TAG != '' && env.OS == 'Ubuntu' }}
        run: bash -eu scripts/CI-Steps/0B-SETUP-Linux-Container.sh

      - name: '1.1-Install-Module.ps1 '
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 1.1-Install-Module.ps1
        if: ${{ !cancelled() }}

      - name: '2-Install-DotNet.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 2-Install-DotNet.ps1
        if: ${{ !cancelled() }}

      - name: '3-Install-SQL-Server.ps1 (Windows only)'
        timeout-minutes: 30
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 3-Install-SQL-Server.ps1
        if: ${{ matrix.OS == 'Windows' }}

      - name: Publish SQL Setup Logs (Windows only)
        if: ${{ matrix.OS == 'Windows' }}
        uses: actions/upload-artifact@v4
        with:
          name: SQL Setup Logs ${{ matrix.SQL }} ${{ github.run_attempt }}
          path: ${{ env.SYSTEM_ARTIFACTSDIRECTORY }}/SQL Setup Logs
          overwrite: true

      - name: '3.1-Install-SQLCMD.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 3.1-Install-SQLCMD.ps1
        if: ${{ matrix.OS == 'Windows' }}

      - name: '4-Publish-Sql-Server-Setup-Logs.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 4-Publish-Sql-Server-Setup-Logs.ps1
        if: ${{ !cancelled() }}

      - name: '5-Configure-SQL-Server.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 5-Configure-SQL-Server.ps1
        if: ${{ !cancelled() }}

      - name: '7-SqlJam-Tests.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 7-SqlJam-Tests.ps1
        if: ${{ !cancelled() }}

      - name: '8-Install-Chrome-on-Windows.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 8-Install-Chrome-on-Windows.ps1
        if: ${{ matrix.OS == 'Windows' }}

      - name: '8-Install-Chrome-on-Linux.sh'
        shell: bash
        run: . ./scripts/CI-Steps/8-Install-Chrome-on-Linux.sh
        if: ${{ matrix.OS != 'Windows' }}
      
        # The Step is optional (Frontend always on Host)
      - name: '9-Run-w3app.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 9-Run-w3app.ps1
        # if: always()
        if: false

        # Frontend always on Host
      - name: 'RUN w3app on host'
        run: |
           pwsh .\scripts\CI-Steps\9-Run-w3app.ps1
           . .\scripts\CI-Steps\Functions.ps1
           Say "PROCESSES: chrome"
           Start-Sleep -Seconds 13
           Show-Chrome-Processes
        if: ${{ !cancelled() }}
        # if: false

        # API on Container
      - name: '10-Run-W3API.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 10-Run-w3api.ps1
        if: ${{ !cancelled() }}

        # It also dumps SqlInsights snapshot, so it is the last
      - name: '6-ErgoFab-Tests.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 6-ErgoFab-Tests.ps1
        if: ${{ !cancelled() && !contains(matrix.SQL, '2005') }}
        # if: always()

        # Warning! It kills all the dotnet processes
      - name: '999-Stop-Apps.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 999-Stop-Apps.ps1
        if: ${{ !cancelled() }}

      - name: '20-Storage-Tests-and-Benchmark.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 20-Storage-Tests-and-Benchmark.ps1
        if: ${{ !cancelled() }}

      - name: '80-Stress-SQL-Server-by-Stored-Procedure.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 80-Stress-SQL-Server-by-Stored-Procedure.ps1
        if: ${{ !cancelled() }}

      - name: '90-Administrative-Views-By-Tool.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 90-Administrative-Views-By-Tool.ps1
        if: ${{ !cancelled() }}

      - name: '91-Administrative-Views-By-Tests.ps1'
        run: . .\scripts\CI-Steps\Run-CI-Script.ps1 91-Administrative-Views-By-Tests.ps1
        if: ${{ !cancelled() }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'If ${{ matrix.JOB_TITLE }}
          path: ${{ env.SYSTEM_ARTIFACTSDIRECTORY }}
          overwrite: true
          compression-level: 9
