name: SqlInsights Windows Matrix

on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  Windows-Job:
    name: ${{ matrix.SQL }}
    runs-on: "windows-${{ matrix.OS }}"
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.matrix) }}
    
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bootstrap
        uses: devizer/devops-library@main
      - name: 'Store Job Name'
        shell: bash
        run: 'echo ${{ matrix.SQL }} | tee $SYSTEM_ARTIFACTSDIRECTORY/JOB-NAME.TXT'
      - name: Download Pre-Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Pre-Build
          path: "${{ github.workspace }}/Goods"

      - name: Show Arguments and Pre-Build Content
        run: |
          Import-DevOps
          Say "SQL: [${{ matrix.SQL }}]"
          Say ".\Goods content"
          ls Goods | ft -autosize
          Say ".\Goods\w3api content"
          ls .\Goods\w3api | ft -autosize
          Say ".\Goods\w3api\wwwroot content"
          ls .\Goods\w3api\wwwroot | ft -autosize
          Say "SYSTEM_ARTIFACTSDIRECTORY content ($ENV:SYSTEM_ARTIFACTSDIRECTORY)"
          ls $ENV:SYSTEM_ARTIFACTSDIRECTORY | ft -autosize

      - name: 'Tune Docker'
        run: Import-DevOps; Run-Remote-Script https://raw.githubusercontent.com/devizer/glist/master/Move-Docker-to-SSD-for-Windows-On-Microsoft-Hosted-Build-Agent.ps1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'If ${{ matrix.SQL }}'
          path: ${{ env.SYSTEM_ARTIFACTSDIRECTORY }}
          overwrite: true
          compression-level: 9
